def trobar_categoria(nom_producte):
    nom_norm = normalitzar_text(nom_producte)
    
    INICI_PRODUCTE = {
        'llet ': 'llet',
        'leche ': 'llet', 
        'iogurt': 'iogurt',
        'yogur': 'iogurt',
        'arroz': 'arros',
        'arros': 'arros',
        'cerveza': 'cervesa',
        'cervesa': 'cervesa',
        'vino tinto': 'vi',
        'vino blanco': 'vi',
        'vino rosado': 'vi',
        'vi negre': 'vi',
        'vi blanc': 'vi',
        'vi rosat': 'vi',
        'cava ': 'cava',
        'atun': 'tonyina',
        'tonyina': 'tonyina',
        'aceite de oliva': 'oli oliva',
        'aceite de girasol': 'oli girasol',
        'huevos': 'ous',
        'ous ': 'ous',
        'pan de molde': 'pa motlle',
        'pa de motlle': 'pa motlle',
        'mantequilla': 'mantega',
        'mantega': 'mantega',
        'azucar': 'sucre',
        'sucre': 'sucre',
        'detergente': 'detergent',
        'detergent ': 'detergent',
        'lejia': 'lleixiu',
        'lleixiu': 'lleixiu',
        'agua mineral': 'aigua',
        'agua con gas': 'aigua',
        'agua sin gas': 'aigua',
        'galletas': 'galetes',
        'galetes': 'galetes',
        'chocolate': 'xocolata',
        'xocolata': 'xocolata',
        'patatas fritas': 'patates',
        'patates fregides': 'patates',
        'tomate frito': 'tomaquet',
        'tomaquet fregit': 'tomaquet',
        'cafe en': 'cafe',
        'cafe molt': 'cafe',
        'macarrones': 'pasta',
        'macarrons': 'pasta',
        'espaguetis': 'pasta',
        'fideos ': 'pasta',
        'fideus ': 'pasta',
        'lasana': 'pasta',
        'lasanya': 'pasta',
    }
    
    for inici, categoria in INICI_PRODUCTE.items():
        if nom_norm.startswith(normalitzar_text(inici)):
            return categoria
    return None
