name: Scraper Part 5 - Carrefour

on:
  schedule:
    - cron: '0 18 * * 1'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper Part 5
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: xvfb-run -a python scraper_main.py --part=5
